import type { Metadata } from "next";
import DashboardSidebar from "@/src/components/dashboard-bar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <DashboardSidebar />
            {children}
        </>
    );
}
