import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { hanken_grotesk, ibm_plex_mono, manrope } from "./fonts";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={manrope.className}>{children}</body>
        </html>
    );
}
