import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { plus_jakarta_sans } from "./fonts";
import DashboardSidebar from "../components/dashboard-bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${plus_jakarta_sans.className} flex`}>
        <DashboardSidebar />
        {children}
      </body>
    </html>
  );
}
